[project]
name = "lambdax-codebase"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.45.2",
    "ipykernel>=6.29.5",
    "python-dotenv>=1.0.1",
    "python-gitlab>=5.6.0",
]
